set(_CATKIN_CURRENT_PACKAGE "ql_test")
set(ql_test_MAINTAINER "amsl <amsl@todo.todo>")
set(ql_test_DEPRECATED "")
set(ql_test_VERSION "0.0.0")
set(ql_test_BUILD_DEPENDS "roscpp" "rospy")
set(ql_test_RUN_DEPENDS "roscpp" "rospy")
set(ql_test_BUILDTOOL_DEPENDS "catkin")