set(_CATKIN_CURRENT_PACKAGE "ql_test2")
set(ql_test2_MAINTAINER "amsl <amsl@todo.todo>")
set(ql_test2_DEPRECATED "")
set(ql_test2_VERSION "0.0.0")
set(ql_test2_BUILD_DEPENDS "roscpp" "rospy")
set(ql_test2_RUN_DEPENDS "roscpp" "rospy")
set(ql_test2_BUILDTOOL_DEPENDS "catkin")